# =================================
# Main settings for the DCASE 2020
# challenge baseline system.
#
# author: Konstantinos Drossos
# affiliation: Tampere University
# =================================
workflow:
  dnn_training: Yes
  dnn_evaluation: Yes
# ---------------------------------
dnn_training_settings: !include method_ht_12_37.yaml
# -----------------------------------
dirs_and_files: !include dirs_and_files_37.yaml
# EOF
